# fly.toml app configuration file generated for hermes-coo on 2026-08-15T22:07:02Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hermes-coo'
primary_region = 'ams'

[processes]
  app = "gateway run"

[[mounts]]
  source = 'data'
  destination = '/opt/data'

[http_service]
  internal_port = 8642
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024
